- name: checking data types
  host: localhost
  vars:
    NAME: Sivaram
    SKILLS: 
    - Devops
    - shell
    - Ansible
    - Linux
    Experience: #Experience is map type. It contains key-value pair
     Devops: 7
     AWS: 6
     Docker: 4
    Trainer: true
  tasks:
  - name: print key value pair
    ansible.builtin.debug:
      msg: "name: {{NAME}}"
  - name: print list
    ansible.builtin.debug:
      msg: "SKILLS: {{SKILLS}}"
  - name: print list
    ansible.builtin.debug:
      msg: "Experience: {{Experience}}"
  - name: print list
    ansible.builtin.debug:
      msg: "Trainer: {{Trainer}}"
