- name: loops
  hosts: localhost
  become: yes
  tasks:
  - name: print the persons
    ansible.builtin.package:
      msg: "{{item}}" #item is a default keyword
      state: present
    loop: 
    - git
    - mysql
    - postfix
    
